### ISSUE TITLE
Cant get elevation map in RViz

### ISSUE THREAD

**Issue by Artinmi** [Muhammad540/elevation_mapping#3]
i appreciate your work ,as i really need to apply this onn my project, im getting my PCl from a realsense depht camera and feed it the elecation map, i also create a pose estimation and pass it the elevarion map ( i have passed PCL and Pose topics to your package) . thats the only modification i have done and then i lunch this node by: ros2 launch elevation_mapping elevationMapping_launch.py . after that i dont recieve the elevation map in the Rviz topics. i moght missed some modifications i will be glad if you guide me

**Comment by Muhammad540** [comment]
first i would suggest ensure that you are receiving the data from the point cloud and pose topics also transform tree is complete. Can you verify from the rqt graph that elevation mapping package is correctly reading all the inputs and publishing output on the elevation map raw topic ?

**Comment by Artinmi** [comment]
thanks dear muhammad, i have maually write a ros2 node that publishes a static pose ( named /pose_2). this my rqt_graph
![Screenshot from 2024-11-21 14-28-23](https://github.com/user-attachments/assets/07d9a9f8-5a56-4686-bf39-4529303c116a)

**Comment by Artinmi** [comment]
you might find these also helpful. the results im getting: ( as you see when i open the topics to add in Rviz the elevation map is off)
![Screenshot from 2024-11-21 14-28-57](https://github.com/user-attachments/assets/74389611-3d01-486b-abc5-1a18d9a90c2a)
![Screenshot from 2024-11-21 14-27-50](https://github.com/user-attachments/assets/9fe2cf14-6fc0-4b9d-958a-0f5488ec6b76)
![Screenshot from 2024-11-21 14-24-09](https://github.com/user-attachments/assets/fc562736-cb00-4d96-b565-c4b8a200d707)

**Comment by Muhammad540** [comment]
my first suggestion try removing the post processing pipeline, just comment out it from the list of files. Secondly, check the topic types. Your pose topic should be of type "nav_msgs/Odometry" and the  point cloud of type sensor_msgs/PointCloud2. Why are you publishing a static pose ? and between what two frames ? The pose topic should be your robots pose estimates from the odom to baselink and they are not static.

**Comment by Artinmi** [comment]
thanks dear muhammad for your help. that was exactly my problem. now everything works fine. well done!
